### PR TITLE
Added 4 More HSPT Problems

### PR DESCRIPTION
**Pull request by gblake31**
Added 4 more problems from HSPT whose input sizes are on the smaller side. These will give us the ability to:
- Remove some of the current problems that are nonfunctional
- Troubleshoot judging speeds when problems have tons of small test cases vs only a few large ones
- Test the new fields (source, author, time, memory)

Added BABA, Contact, Diamond, and Through from HSPT Online 23-24'

image

### CODE REVIEW

**Comment by gblake31** [comment]
image

**Comment by gblake31** [comment]
image
image

**Comment by gblake31** [comment]
image
image

**Review by AsirAAlam — APPROVED** [review]
Glad to see the Problem Creator in action 🙂

**Comment by gblake31** [comment]
> Glad to see the Problem Creator in action 🙂

Yessir!! It's so helpful.

**Pull request merged**
